// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using FINAPSA.Data;

#nullable disable

namespace FINAPSA.Migrations
{
    [DbContext(typeof(FINAPSADbContext))]
    [Migration("20260424120000_AddCascadeDeleteForTransactionLogs")]
    partial class AddCascadeDeleteForTransactionLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This is a partial migration - the full model would be in FINAPSADbContextModelSnapshot
            // This migration only changes the TransactionLog -> Payment foreign key to use Cascade delete
#pragma warning restore 612, 618
        }
    }
}
